markfasheh/ocfs2-tools

o2cb_ctl/o2cb_scandisk.c

Allow global heartbeat on /dev/vd Virtio devices inside KVM.
This is equivalent to /dev/xvd device support previously added for Xen.

ocfs2-tools: add support for vd devices

---

debugfs.ocfs2/main.c

$ /sbin/debugfs.ocfs2 --superblock
Segmentation fault

debugfs.ocfs2: fix command line segfault

---

mkfs.ocfs2/mkfs.c

$ /sbin/mkfs.ocfs2 --journal
Segmentation fault

mkfs.ocfs2: fix command line segfault

---

o2monitor/o2hbmonitor.c
vendor/common/o2cb.init.sh

This was changed in the kernel a while ago so the heartbeat config currently looks like this (kernel 4.9.13):
```
$ ls -l /sys/kernel/config/cluster/ocfs2/heartbeat
drwxr-xr-x 2 root root    0 Mar 24 18:53 00831BDF77A04E4EBB619359FE5A4CAA
-rw-r--r-- 1 root root 4096 Mar 24 19:19 mode
-rw-r--r-- 1 root root 4096 Mar 24 19:19 threshold
```

Update sysfs filename for heartbeat dead threshold

---

o2monitor/o2hbmonitor.c
vendor/common/o2cb.init.sh

Reverts markfasheh/ocfs2-tools#9
This is a kernel issue, fix from kernel side.

Revert "Update sysfs filename for heartbeat dead threshold"

---

Makefile

Split SUBDIRS into groups that can be built in parallel,
so that something like 'make -j8' now works correctly.
Fixes github issue #12

Makefile: allow parallel builds

---

libocfs2/chain.c

fsck.ocfs2 will fall in dead loop when a loop exists in group chain allocator.
To fix this, just limit max loop count in ocfs2_cache_chain_allocator_blocks.

fix fsck.ocfs2 fall in deadloop when encounter a loop chain 

---

mounted.ocfs2/mounted.c

mounted.c: In function ‘build_partition_list’:
mounted.c:354:13: warning: In the GNU C Library, "makedev" is defined
by <sys/sysmacros.h>. For historical compatibility, it is
currently defined by <sys/types.h> as well, but we plan to
remove this soon. To use "makedev", include <sys/sysmacros.h>
directly. If you did not intend to use a system-defined macro
"makedev", you should undefine it after including <sys/types.h>.
makedev(major, minor), &devname);
^~~~~~~~~~~~~~~~~~~~~~~~~~~

mounted.ocfs2: use <sys/sysmacros.h> include for makedev

---

vendor/common/o2cb.init.sh

The $LOADED_PLUGINS_FILE disappears after unloading
modules and the read returns an error:
...
Unloading module "ocfs2_dlmfs": OK
Unloading module "ocfs2_stack_o2cb": OK
/usr/lib/ocfs2-tools/o2cb: line 1151: read: read error: 0: No such device

o2cb.init: Fix error printed by service o2cb stop

---

debugfs.ocfs2/debugfs.ocfs2.8.in
fsck.ocfs2/extent.c
fsck.ocfs2/fsck.c
fsck.ocfs2/fsck.ocfs2.8.in
fsck.ocfs2/fsck.ocfs2.checks.8.in
fsck.ocfs2/pass0.c
fsck.ocfs2/pass1b.c
fsck.ocfs2/pass2.c
fsck.ocfs2/refcount.c
libo2cb/o2cb.7.in
libocfs2/ocfs2.7.in
libocfs2/ocfs2_err.et
mkfs.ocfs2/mkfs.ocfs2.8.in
mounted.ocfs2/mounted.c
o2cb_ctl/ocfs2.cluster.conf.5.in
o2info/o2info.1.in
tunefs.ocfs2/feature_indexed_dirs.c
tunefs.ocfs2/feature_quota.c
tunefs.ocfs2/o2cluster.8.in
tunefs.ocfs2/o2cluster.c
vendor/common/o2cb.sysconfig.5.in

Spelling errors reported by lintian check of the
Debian package.

Fix spelling in documentation and binary strings

---

tunefs.ocfs2/Makefile

Parallel build (make -j 10) sometimes fails with an error:
o2cluster.c:32:10: fatal error: o2ne_err.h: No such file or directory
#include "o2ne_err.h"
^~~~~~~~~~~~
compilation terminated
make[2]: *** [../Postamble.make:40: o2cluster.o] Error 1
So add a missing depends for o2cluster.o on o2ne_err.h.

tunefs.ocfs2: fix parallel build

---

libo2dlm/o2dlm.c

Because libdlm_lt.so is only shipped in the development libdlm-dev package.

libo2dlm: dlopen libdlm_lt.so.3 instead of libdlm_lt.so

---

defragfs.ocfs2/main.c

Deleting list elements requires list_for_each_safe or the parameter list
gets destroyed:
$ defragfs.ocfs /tmp
defragfs.ocfs2 1.8.6
"/tmp":Not within ocfs2 fs
Failed to get file info:: Bad address
Segmentation fault

defragfs.ocfs2: fix command line segfault

---

defragfs.ocfs2/main.c

Fixes #42
From ISO/IEC 9899:1999 (E):
6.3.1.3 Signed and unsigned integers
1 When a value with integer type is converted to another integer type
other than _Bool, if the value can be represented by the new type, it is
unchanged.
2 Otherwise, if the new type is unsigned, the value is converted by
repeatedly adding or subtracting one more than the maximum value that
can be represented in the new type until the value is in the range of
the new type.
3 Otherwise, the new type is signed and the value cannot be represented
in it; either the result is implementation-defined or an
implementation-defined signal is raised.
gcc-9-aarch64-linux-gnu 9.2.1 makes ((char = getopt()) != EOF) to always
compare (255 != -1), considering char to be unsigned, as states item
(3): implementation-defined. Meaning …

defragfs.ocfs2: make getopt return variable portable

---

o2image/o2image.c

Use correct union member. On little endian this worked only because of the union layout.
Fixes #22 o2image fails on s390x (big endian)
Signed-off-by: Valentin Vidic <vvidic@debian.org>

o2image: Fix segfault on s390x

---

libocfs2/dir_indexed.c

When we try to create a directory index tree, we should truncate
the directory index tree if this creation failed for some reason,
e.g. there is not any more blocks to allocate.
Otherwise, the file was attached a problematic directory index
tree, this index will affect file lookup under this directory file.

libocfs2: roll-back when dir_index creation fails

---

debugfs.ocfs2/dump_fs_locks.c

3 years ago, the kernel implementation added 4:
https://github.com/torvalds/linux/commit/8a7f5f4c26dd4e969b5f3b30d06c54dc6a520eda#diff-763516839c283f4678cde681fcdba36b4f99f41ad05087b4ee3d8cf569680171
So dump_fs_locks doesnt work against that and fails due to the version being higher than expected.

dump_fs_locks: support v4

---

debugfs.ocfs2/commands.c
debugfs.ocfs2/debugfs.ocfs2.8.in
debugfs.ocfs2/dump.c
debugfs.ocfs2/include/dump.h
debugfs.ocfs2/include/utils.h
debugfs.ocfs2/stat_sysdir.c
debugfs.ocfs2/utils.c
include/ocfs2-kernel/ocfs2_fs.h

This commit introduces new feature for debugfs.ocfs2, which could record contiguous free bits for each //global_bitmap group descriptor block.
It's very useful for the users who want to speed up IO performance, when ocfs2 volume fragmentation rate is high.
Please note, this commit requires kernel supporting 'struct ocfs2_group_desc' new member 'bg_contig_free_bits'.

debugfs.ocfs2: support recording gd bg_contig_free_bits

---

libocfs2/extents.c

One of our customers reported read-only filesystem. fsck.ocfs2 -ny showed the following issue:
Pass 1: Checking inodes and blocks
[EXTENT_LIST_FREE] Extent list in owner 658435 claims 231 as the next free chain record, but fsck believes the largest valid value is 227.  Clamp the next record value? n
debugfs.ocfs2 also showed the corruption:
Inode: 658435   Mode: 0644   Generation: 974589382 (0x3a170dc6)
FS Generation: 432631804 (0x19c96ffc)
CRC32: 00000000   ECC: 0000
Type: Regular   Attr: 0x0   Flags: Valid
Dynamic Features: (0x0)
User: 0 (root)   Group: 0 (root)   Size: 121633767424
Links: 1   Clusters: 14848000
ctime: 0x66fa60d8 0x343acc43 -- Mon Sep 30 08:27:04.876268611 2024
atime: 0x66fa5e5d 0x34514ed8 -- Mon Sep 30 08:16:29.877743832 2024
mtime: 0x66fa60d8 0x343acc43 -- Mon Sep 30 …

libocfs2: fix non-zero value in Next Leaf field in the rightmost leaf metadata block

---

vendor/common/o2cb.init.sh

This is causing an ENOENT error message in o2cb.init even though everything works just fine. The file /etc/init.d/functions has been removed from the distros long ago. Removing the unwanted legacy, non-existent references.

o2cb.init: remove unwanted legacy /etc/init.d/functions
